### ISSUE TITLE
How to load multiple data/policy sets in DynamoDb

### ISSUE THREAD

**Issue by swathit0717** [mneil/opa-dynamodb#17]
Hi, 

I have tried out Opa with Dynamodb as mentioned in the " https://mneil.github.io/opa-dynamodb" . It works fine. My requirement is I have multiple applications with each one having related data and policies. As per the example mentioned Opa can connect to only one table which is "TABLE_NAME: OpaDynamoDB". Does this implementation supports my requirement. As I am very new to OPA, I would like to know if there is any example as such to insert multiple datasets and corresponding policies into Dynamodb and retrieve it.

**Comment by mneil** [comment]
Yes, you can use opa-dynamodb with multiple applications. All policies for all applications though would need to live in a single dynamodb table.

Fortunately, dynamodb is great at this.

I'm the examples there is a key "foo/bar" and a user, Alice. Imagine that alice exists in multiple applications. You can use the key to denote whichever application you want and Alice is always the user. 

In rego you can pull in multiple polices from different namespaces in a single file. Or, you can create a new policy for reach namespace and query them separately.

Does that address what you're looking for?
